### PR TITLE
Todo list review

### PR DESCRIPTION
**Pull request by husush23**
In this branch I shared Combined files of my todo list

### CODE REVIEW

**Review by ANTOINE1128 — COMMENTED** [review]
Hi @husush23 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

Alt Text

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ANTOINE1128** [comment]
https://github.com/husush23/Todo-list-review/blob/f67a31a4655530cd17e13e4285d369c38b9de83d/index.html#L12

 kindly consider taking a second look at your CSS loader as unsure what exactly the problem might be but your style.css isn't loading and due to that your page looks like you didn't add any styles at all. Fixing the styles issue will make your design more attractive to your user and create a good user experience. See below for more details:

**Comment by husush23** [comment]
@ANTOINE1128  thank you for pointing out those things and I will fix it.

**Review by ANTOINE1128 — APPROVED** [review]
Hi @husush23  ,
Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉

Highlights
Descriptive pull request message with screenshots ✔️
Well organized project ✔️
approval
Status: Approved ✔️✔️✔️
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100%.
Please, remember to tag me @ANTOINE1128 in your question so I can receive the notification.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Pull request merged**
